# personal bottom config

# =========
# = flags =
# =========

[flags]
# common
dot_marker = false
rate = 1000
case_sensitive = false
whole_word = false
regex = true
default_widget_type = "proc"
default_widget_count = 1
show_table_scroll_position = false
disable_click = false
default_time_value = 60000
time_delta = 15000
hide_time = false
basic = false
hide_table_gap = false

# cpu
hide_avg_cpu = false
left_legend = false
current_usage = false

# temperature
#temperature_type = "k"
#temperature_type = "f"
#temperature_type = "c"
#temperature_type = "kelvin"
#temperature_type = "fahrenheit"
temperature_type = "celsius"

# battery
battery = true

# network
use_old_network_legend = false
network_use_binary_prefix = false
network_use_bytes = false
network_use_log = false

# progress
process_command = false
group_processes = false
tree = false
mem_as_value = false
disable_advanced_kill = false

# color themes
# Built-in themes.  Valid values are "default", "default-light", "gruvbox", "gruvbox-light", "nord", "nord-light"
color = "nord"


# ================
# = theme colors =
# ================

#[colors] # Uncomment if you want to use custom colors
# Represents the colour of table headers (processes, CPU, disks, temperature).
#table_header_color="LightBlue"
# Represents the colour of the label each widget has.
#widget_title_color="Gray"
# Represents the average CPU color.
#avg_cpu_color="Red"
# Represents the colour the core will use in the CPU legend and graph.
#cpu_core_colors=["LightMagenta", "LightYellow", "LightCyan", "LightGreen", "LightBlue", "LightRed", "Cyan", "Green", "Blue", "Red"]
# Represents the colour RAM will use in the memory legend and graph.
#ram_color="LightMagenta"
# Represents the colour SWAP will use in the memory legend and graph.
#swap_color="LightYellow"
# Represents the colour rx will use in the network legend and graph.
#rx_color="LightCyan"
# Represents the colour tx will use in the network legend and graph.
#tx_color="LightGreen"
# Represents the colour of the border of unselected widgets.
#border_color="Gray"
# Represents the colour of the border of selected widgets.
#highlighted_border_color="LightBlue"
# Represents the colour of most text.
#text_color="Gray"
# Represents the colour of text that is selected.
#selected_text_color="Black"
# Represents the background colour of text that is selected.
#selected_bg_color="LightBlue"
# Represents the colour of the lines and text of the graph.
#graph_color="Gray"
# Represents the colours of the battery based on charge
#high_battery_color="green"
#medium_battery_color="yellow"
#low_battery_color="red"



# ==========
# = Filter =
# ==========

[disk_filter]
is_list_ignored = false
list = ["/dev/sda\\d+", "/dev/nvme0n1p2"]
regex = true
case_sensitive = false
whole_word = false

[mount_filter]
is_list_ignored = false
list = ["/mnt/.*", "/boot"]
regex = true
case_sensitive = false
whole_word = false

[temp_filter]
is_list_ignored = false
list = ["cpu", "wifi"]
regex = false
case_sensitive = false
whole_word = false

[net_filter]
is_list_ignored = true
list = ["virbr0.*"]
regex = true
case_sensitive = false
whole_word = false



# ==========
# = Layout =
# ==========

# All widgets must have the type value set to one of ["cpu", "mem", "proc", "net", "temp", "disk", "empty"].
[[row]]
  ratio=1
  [[row.child]]
    ratio=1
    type="cpu"
[[row]]
  ratio=1
  [[row.child]]
    ratio=1
    type="net"
  [[row.child]]
    ratio=1
    type="batt"
  [[row.child]]
    ratio=1
    [[row.child.child]]
      ratio=1
      type="temp"
    [[row.child.child]]
      ratio=1
      type="disk"
[[row]]
  ratio=1
  [[row.child]]
    ratio=1
    type="mem"
  [[row.child]]
    ratio=1
    [[row.child.child]]
      ratio=1
      type="proc"

